services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - lake
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 30

  mc:
    image: minio/mc:latest
    container_name: mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./files:/files:ro
    networks:
      - lake
    entrypoint: >
      /bin/sh -c "
      set -e;
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb -p local/data || true;
      mc mb -p local/reports || true;
      mc cp /files/Ref.xlsx local/data/ref/Ref.xlsx;
      mc cp /files/REF_CBS_SMS2.csv local/data/REF_SMS/REF_CBS_SMS2.csv;
      mc stat local/data/REF_SMS/REF_CBS_SMS2.csv;
      mc stat local/data/ref/Ref.xlsx;
      echo 'seed done';
      "
    healthcheck:
      test: ["CMD-SHELL", "mc alias set local http://minio:9000 minioadmin minioadmin123 >/dev/null 2>&1 && mc stat local/data/REF_SMS/REF_CBS_SMS2.csv >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30

  spark-master:
    build: ./spark
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./jobs:/opt/spark/jobs
    networks:
      - lake

  spark-worker:
    build: ./spark
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
    ports:
      - "8081:8081"
    volumes:
      - ./jobs:/opt/spark/jobs
    networks:
      - lake

  spark-job:
    build: ./spark
    container_name: spark-job
    restart: "no"
    depends_on:
      minio:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
      spark-master:
        condition: service_started
      spark-worker:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
    volumes:
      - ./jobs:/opt/spark/jobs
    networks:
      - lake
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      /opt/spark/jobs/reports_jobs.py 

volumes:
  minio_data:

networks:
  lake:
    driver: bridge
